let boom = [];
for (let i=0; i<100; i++){
  if(i%7===0 || (i-7)%10===0){
    boom.push("boom")
  }else{
    boom.push(i)
  }
}

new Vue({
    el: '#app',
    data: {
      boom:boom,
      n:10,
      people: [{
        "first_name": "Sebastian",
        "last_name": "Malser",
        "email": "smalser0@phoca.cz",
        "gender": "Male"
      }, {
        "first_name": "Nadia",
        "last_name": "Shoveller",
        "email": "nshoveller1@marriott.com",
        "gender": "Female"
      }, {
        "first_name": "Franklyn",
        "last_name": "Wrassell",
        "email": "fwrassell2@theatlantic.com",
        "gender": "Male"
      }, {
        "first_name": "Sashenka",
        "last_name": "Quest",
        "email": "squest3@apache.org",
        "gender": "Female"
      }, {
        "first_name": "Manny",
        "last_name": "Vettore",
        "email": "mvettore4@devhub.com",
        "gender": "Male"
      }, {
        "first_name": "Cary",
        "last_name": "Clack",
        "email": "cclack5@gravatar.com",
        "gender": "Male"
      }, {
        "first_name": "Cal",
        "last_name": "Cassels",
        "email": "ccassels6@posterous.com",
        "gender": "Male"
      }, {
        "first_name": "Zorana",
        "last_name": "Sowood",
        "email": "zsowood7@huffingtonpost.com",
        "gender": "Female"
      }, {
        "first_name": "Tristam",
        "last_name": "Ridout",
        "email": "tridout8@meetup.com",
        "gender": "Male"
      }, {
        "first_name": "Nikolai",
        "last_name": "Blyth",
        "email": "nblyth9@telegraph.co.uk",
        "gender": "Male"
      }, {
        "first_name": "Leena",
        "last_name": "Reedie",
        "email": "lreediea@cmu.edu",
        "gender": "Female"
      }, {
        "first_name": "Weider",
        "last_name": "Creany",
        "email": "wcreanyb@webmd.com",
        "gender": "Male"
      }, {
        "first_name": "Rudie",
        "last_name": "Brushfield",
        "email": "rbrushfieldc@freewebs.com",
        "gender": "Male"
      }, {
        "first_name": "Stanford",
        "last_name": "Anstie",
        "email": "sanstied@biglobe.ne.jp",
        "gender": "Male"
      }, {
        "first_name": "Lotte",
        "last_name": "Dollard",
        "email": "ldollarde@mail.ru",
        "gender": "Female"
      }, {
        "first_name": "Whitaker",
        "last_name": "Callan",
        "email": "wcallanf@dedecms.com",
        "gender": "Male"
      }, {
        "first_name": "Randy",
        "last_name": "Gewer",
        "email": "rgewerg@jalbum.net",
        "gender": "Female"
      }, {
        "first_name": "Brenden",
        "last_name": "Kynge",
        "email": "bkyngeh@mlb.com",
        "gender": "Male"
      }, {
        "first_name": "Maribel",
        "last_name": "Cufflin",
        "email": "mcufflini@miibeian.gov.cn",
        "gender": "Female"
      }, {
        "first_name": "Bjorn",
        "last_name": "Simonson",
        "email": "bsimonsonj@techcrunch.com",
        "gender": "Male"
      }, {
        "first_name": "Van",
        "last_name": "Phillps",
        "email": "vphillpsk@friendfeed.com",
        "gender": "Male"
      }, {
        "first_name": "Gaston",
        "last_name": "Marzellano",
        "email": "gmarzellanol@dot.gov",
        "gender": "Male"
      }, {
        "first_name": "Hy",
        "last_name": "Curnnok",
        "email": "hcurnnokm@ftc.gov",
        "gender": "Male"
      }, {
        "first_name": "Roxanna",
        "last_name": "Eskell",
        "email": "reskelln@posterous.com",
        "gender": "Female"
      }, {
        "first_name": "Collin",
        "last_name": "De Vile",
        "email": "cdevileo@geocities.com",
        "gender": "Male"
      }, {
        "first_name": "Filia",
        "last_name": "Ogilvy",
        "email": "fogilvyp@globo.com",
        "gender": "Female"
      }, {
        "first_name": "Elsa",
        "last_name": "Shelmerdine",
        "email": "eshelmerdineq@japanpost.jp",
        "gender": "Female"
      }, {
        "first_name": "Kleon",
        "last_name": "Castanos",
        "email": "kcastanosr@kickstarter.com",
        "gender": "Male"
      }, {
        "first_name": "Clemente",
        "last_name": "Karlicek",
        "email": "ckarliceks@nydailynews.com",
        "gender": "Male"
      }, {
        "first_name": "Stacee",
        "last_name": "McKane",
        "email": "smckanet@jiathis.com",
        "gender": "Male"
      }, {
        "first_name": "Odelinda",
        "last_name": "Petrello",
        "email": "opetrellou@marriott.com",
        "gender": "Female"
      }, {
        "first_name": "Denny",
        "last_name": "Leggott",
        "email": "dleggottv@bravesites.com",
        "gender": "Male"
      }, {
        "first_name": "Stillman",
        "last_name": "Jermy",
        "email": "sjermyw@eepurl.com",
        "gender": "Male"
      }, {
        "first_name": "Etta",
        "last_name": "Molen",
        "email": "emolenx@cyberchimps.com",
        "gender": "Female"
      }, {
        "first_name": "Christel",
        "last_name": "Farny",
        "email": "cfarnyy@spiegel.de",
        "gender": "Female"
      }, {
        "first_name": "Fredericka",
        "last_name": "Duiguid",
        "email": "fduiguidz@ucoz.com",
        "gender": "Female"
      }, {
        "first_name": "Davida",
        "last_name": "Robelow",
        "email": "drobelow10@soup.io",
        "gender": "Female"
      }, {
        "first_name": "Palm",
        "last_name": "Debnam",
        "email": "pdebnam11@xing.com",
        "gender": "Male"
      }, {
        "first_name": "Hollie",
        "last_name": "Appleby",
        "email": "happleby12@amazon.co.jp",
        "gender": "Female"
      }, {
        "first_name": "Stearn",
        "last_name": "Wordsworth",
        "email": "swordsworth13@technorati.com",
        "gender": "Male"
      }, {
        "first_name": "Chick",
        "last_name": "Egle",
        "email": "cegle14@shop-pro.jp",
        "gender": "Male"
      }, {
        "first_name": "Misha",
        "last_name": "Carlucci",
        "email": "mcarlucci15@noaa.gov",
        "gender": "Female"
      }, {
        "first_name": "Skippy",
        "last_name": "Roycroft",
        "email": "sroycroft16@who.int",
        "gender": "Male"
      }, {
        "first_name": "Nathan",
        "last_name": "Sibray",
        "email": "nsibray17@mediafire.com",
        "gender": "Male"
      }, {
        "first_name": "Filippa",
        "last_name": "Bener",
        "email": "fbener18@hubpages.com",
        "gender": "Female"
      }, {
        "first_name": "Cassey",
        "last_name": "Steere",
        "email": "csteere19@hud.gov",
        "gender": "Female"
      }, {
        "first_name": "Lanny",
        "last_name": "Purvis",
        "email": "lpurvis1a@artisteer.com",
        "gender": "Male"
      }, {
        "first_name": "Ginger",
        "last_name": "Cainey",
        "email": "gcainey1b@twitter.com",
        "gender": "Female"
      }, {
        "first_name": "Deerdre",
        "last_name": "Denzey",
        "email": "ddenzey1c@virginia.edu",
        "gender": "Female"
      }, {
        "first_name": "Marylinda",
        "last_name": "Salkild",
        "email": "msalkild1d@wiley.com",
        "gender": "Female"
      }]
    }
  })